### ISSUE TITLE
Update Model V2: Add xp daily diff evaluation. 

### ISSUE THREAD

**Issue by Ferrariic** [Bot-detector/Bot-Detector-Core-Files#136]
I would like to add, as a potential improvement, xp daily diff as a feature. 

This feature would be >75% xp in skilldiff/totaldiff per day averaged for a week. 

This will require: 
- data cleaning 
- feature additions
- dask in place of pandas for server ram
- OVH server instead of linode
- MOAR RAM!
- Fix auto-train. 

Improvements should be tangible. 0.8 correlation in testing.

**Comment by extreme4all** [comment]
not part of api
