### ISSUE TITLE
FastAPI /stats/contributions Not returning correct figures

### ISSUE THREAD

**Issue by ThorntonMatthewD** [Bot-detector/Bot-Detector-Core-Files#144]
Total Uploads is missing some entries.
Feedback sent, possible bans, confirmed bans for auto and manual are all set to 0.

Where the issue probably is:
https://github.com/Bot-detector/Bot-Detector-Core-Files/blob/67a5c7b7659fb8baf833c914c6f015cc55a7b57f/routers/legacy.py#L307

**Comment by extreme4all** [comment]
might be because it limits on 100 000 000 rows, ideally we have it loop until no rows are returned.
https://github.com/Bot-detector/Bot-Detector-Core-Files/blob/67a5c7b7659fb8baf833c914c6f015cc55a7b57f/routers/legacy.py#L160

**Comment by extreme4all** [comment]
pretty sure it was a query issue
