### ISSUE TITLE
rethink security model

### ISSUE THREAD

**Issue by extreme4all** [Bot-detector/Bot-Detector-Core-Files#147]
Currently we have a bit column that sets the permission for a user, to add or remove permissions (levels)(not of a user), we have to update the table, i think it would be easier to have 3 tables, permissions, users, user_permissions.
permissions would hold the unique permissions, users would hold the unique users (name, token), user permissions is the mapping of the user and permission table, one user can have many permissions

**Comment by Ferrariic** [comment]
I think one table is fine  - and seems to work very well at the moment. Multiple tables may not be necessary as it seems overcomplicated for the actual purpose.

**Comment by extreme4all** [comment]
right now we need to update the table if we want to add or remove entitlements, because it is a column value, if it is a row value we can easily add, remove, change a row, making the permissions more modular.

**Comment by extreme4all** [comment]
so there is a table with the api users
```
id;user_name; token; created_at; expire_at
```
there is a table with permissions
```
id; permission
```
and a table where permission & api users are mapped
```
id; user_id; permission_id
```
We also need a table to track the requests of a user:
```
id; user_id; timestamp; route
```

**Comment by Ferrariic** [comment]
Would also like to add last-used, date-created, ratelimit, and active-inactive, and decay (set inactive) any tokens not used within a 30 day timeframe.

**Comment by extreme4all** [comment]
last used, can be gotten from the "request" table
`select max(timestamp) from table where user_id=123`

1. Do you want to have diffrent ratelimits by user?
2. Active/inactive can be checked if currentdate > expiredate

**Comment by Ferrariic** [comment]
Diff ratelimits depending on user level perm probably. Owner level dev unlimited RL, & then we can probably default to a set amount based route itself if not owner.

**Comment by extreme4all** [comment]
okay so on the api_users table we also need rate_limit
`id;user_name; token; created_at; expire_at; rate_limit`

then on each request we need to get the amount of requests of the user in interval T and compare it to the ratelimit

**Comment by Ferrariic** [comment]
Sounds good, yes can be done. I'll set it up shortly on dev.

**Comment by Ferrariic** [comment]
Tables have been created.
