### ISSUE TITLE
Attempt to Create Prediction if One Doesn't Exist

### ISSUE THREAD

**Issue by ThorntonMatthewD** [Bot-detector/Bot-Detector-Core-Files#168]
1. Check if prediction exists
2. Ask ML repo app to make one via remote request
3. If it can't create a prediction (no data on the account or whatever else) return a "blank" prediction so that the plugin doesn't freak out.

Blank prediction format:
```
predict_dict = {
                "player_id": -1,
                "player_name": player_name,
                "prediction_label": "Prediction not in database",
                "prediction_confidence": 0
            }
 ```

**Comment by extreme4all** [comment]
is the issue that we are not handling the "blank" prediction?

**Comment by ThorntonMatthewD** [comment]
Originally. That is been fixed in the legacy routes, but remains an issue in GET /v1/prediction.

**Comment by extreme4all** [comment]
ah, nice catch!

the story would be as a user i don't want to see an api error if the user is not in the database
