### ISSUE TITLE
Have the names column in the Predictions table contain normalized names.

### ISSUE THREAD

**Issue by ThorntonMatthewD** [Bot-detector/Bot-Detector-Core-Files#170]
I'd like for the `POST /v1/prediction` route in the FastAPI port to normalize the names in each list of predictions it receives from the ML app before persisting them to the database.

[This method](https://github.com/Bot-detector/Bot-Detector-Core-Files/blob/57f20da16df0cf4ec99386a83045d2c48be82bea/api/routers/legacy.py#L462) already exists in legacy.py, and is how I'd like the names to be normalized. This will make it much easier to fetch predictions for accounts with special characters (- and _ mostly) in their names.

In the Flask version of our API we select the account's player ID and use that to locate the prediction, which is why it hasn't been an issue up until now. As it is written now, the `GET /v1/prediction` route utilizes a name string and due to inconsistencies in our name formatting we may run into issues where the API cannot locate a prediction if we do not normalize the names in the Predictions table first.

**Comment by extreme4all** [comment]
the ML pulls data from the api, and posts that data with the predictions.
on the api side we don't have to do anything.

**Comment by Ferrariic** [comment]
Since this is wontfix I'll close it. If this is needed we can re-open the issue.
