### ISSUE TITLE
!kc/Get Contributions - Use normalized name

### ISSUE THREAD

**Issue by ThorntonMatthewD** [Bot-detector/Bot-Detector-Core-Files#188]
https://github.com/Bot-detector/Bot-Detector-Core-Files/blob/dd6f890e90999dde183ea31952ab8f996bb92994/api/routers/legacy_debug.py#L166

Change this to ```
    query = ("""
        SELECT
            rs.manual_detect as detect,
            rs.reportedID as reported_ids,
            ban.confirmed_ban as confirmed_ban,
            ban.possible_ban as possible_ban,
            ban.confirmed_player as confirmed_player
        FROM Reports as rs
        JOIN Players as pl on (pl.id = rs.reportingID)
        join Players as ban on (ban.id = rs.reportedID)
        WHERE 1=1
            AND pl.normalized_name in :contributors
    """)
    ```
    
We probably want the endpoints 

https://github.com/Bot-detector/Bot-Detector-Core-Files/blob/dd6f890e90999dde183ea31952ab8f996bb92994/api/routers/legacy_debug.py#L283

(There is a GET and POST) to normalized the name using the to_jagex_name method so we don't have to trust clients to normalize the names the correct way.

**Comment by ThorntonMatthewD** [comment]
There is some name normalization junk in the !kc method on the Discord bot that we can remove if we do this.

**Comment by extreme4all** [comment]
we don't want to change to normalized_name rather we want to cleanup the db so we can use name

**Comment by Ferrariic** [comment]
I noticed that a couple checks on the routes use {1,13} regex, should this be {1,12?}

**Comment by ThorntonMatthewD** [comment]
The 13 length is for `AnonymousUser`.

**Comment by Ferrariic** [comment]
tyvm

**Comment by extreme4all** [comment]
phase out "planned"
