### ISSUE TITLE
Hiscores scraper not inserting

### ISSUE THREAD

**Issue by ThorntonMatthewD** [Bot-detector/Bot-Detector-Core-Files#201]
~~Our last hiscores insert was on November 28th.~~ Okay, I didn't realize what date it was. But our confirmed bans numbers are super low and I'm not sure what's going on.

**Comment by extreme4all** [comment]
maybe some model drift?

**Comment by extreme4all** [comment]
open checking last hiscores are 2021-11-21 22:22:47 and not today..
