### ISSUE TITLE
Add hiscores values for Next kc.

### ISSUE THREAD

**Issue by ThorntonMatthewD** [Bot-detector/Bot-Detector-Core-Files#216]
Nex will be released on January 5th. Jagex will be adding a Nex killcount entry to the hiscores. We can assume it will go in between Mimic and Nightmare in the output from the hiscores lite endpoint.

Our SQL model will need this column added (and of course we will need to create this column in our database too).

**Comment by Ferrariic** [comment]
Good call on making an issue for this, great stuff :D

**Comment by ThorntonMatthewD** [comment]
I don't think the ordering of the entries matters anymore on the API end since the keys are parsed into the model by name.

As long as it's "nex" in both the API model and input_list.py over on the scraper repo it should be okay as far as input goes.

**Comment by extreme4all** [comment]
the following needs to change 
scraper
api models
all db tables & triggers
ml

**Comment by extreme4all** [comment]
this is not a release
