### ISSUE TITLE
Db & api change name values to normalized name values

### ISSUE THREAD

**Issue by extreme4all** [Bot-detector/Bot-Detector-Core-Files#217]
the players table name of a users should be modified to be the normalized name.
the api should use the name value

**Comment by extreme4all** [comment]
cleanup these duplicate names query:

```
select 
	count(*),
    normalized_name
from Players pl 
group by normalized_name
having count(*) > 1
limit 100000
;
```

**Comment by Ferrariic** [comment]
Actually I did some thinking, it's fine how it is.

We can use the normalized_name for our own logic, and the Name for returning properly capitalized strings to players. 

Ex. "Tell me about Ferrariic"
System: Checks "ferrariic"
Returns: "Ferrariic"
Just an idea.

**Comment by ThorntonMatthewD** [comment]
If we keep the current name column then it might be a good idea to rename it to something like `display_name` to prevent confusion, and perhaps go a step further and make `normalized_name` -> `name`.

**Comment by extreme4all** [comment]
phase out planned
