### ISSUE TITLE
update readme

### ISSUE THREAD

**Issue by extreme4all** [Bot-detector/Bot-Detector-Core-Files#238]
the readme should have an update to more show the architecture & process

**Comment by Ferrariic** [comment]
What would you like to see in the new readme specifically?

**Comment by Ferrariic** [comment]
Actually, if you could send me a clear paper diagram of what you would like to see - I'll implement it.

**Comment by extreme4all** [comment]
well updated workflow that kind of stuf

**Comment by Ferrariic** [comment]
Kk I'll take a look at doing this

**Comment by Ferrariic** [comment]
![image](https://user-images.githubusercontent.com/5789682/147987515-d57a868e-7f83-4353-91f2-f6500f851fb8.png)
Working on revising this, here's a draft

**Comment by extreme4all** [comment]
duplicate #391
