### ISSUE TITLE
long_query_time is set to 10 seconds or more, thus only slow queries that take above 10 seconds are logged.

### ISSUE THREAD

**Issue by Ferrariic** [Bot-detector/Bot-Detector-Core-Files#253]
Issue:
long_query_time is set to 10 seconds or more, thus only slow queries that take above 10 seconds are logged.
Recommendation:
It is suggested to set long_query_time to a lower value, depending on your environment. Usually a value of 1-5 seconds is suggested.
Justification:
long_query_time is currently set to 20s.
Used variable / formula:
long_query_time
Test:
value >= 10

**Comment by Ferrariic** [comment]
This is fine tbh. We likely don't want to have short queries spamming our logs. Could even set it to 30s as that's when lockout is.

**Comment by extreme4all** [comment]
not part of api layer
