### ISSUE TITLE
Suboptimal caching method.

### ISSUE THREAD

**Issue by Ferrariic** [Bot-detector/Bot-Detector-Core-Files#254]
Issue:
Suboptimal caching method.
Recommendation:
You are using the MySQL Query cache with a fairly high traffic database. It might be worth considering to use memcached instead of the MySQL Query cache, especially if you have multiple slaves.
Justification:
The query cache is enabled and the server receives 324 queries per second. This rule fires if there is more than 100 queries per second.
Used variable / formula:
Questions / Uptime
Test:
value > 100

**Comment by extreme4all** [comment]
not api related
