### ISSUE TITLE
Too many sorts are causing temporary tables.

### ISSUE THREAD

**Issue by Ferrariic** [Bot-detector/Bot-Detector-Core-Files#256]
Issue:
Too many sorts are causing temporary tables.
Recommendation:
Consider increasing sort_buffer_size and/or read_rnd_buffer_size, depending on your system memory limits.
Justification:
1914% of all sorts cause temporary tables, this value should be lower than 10%.
Used variable / formula:
Sort_merge_passes / (Sort_scan + Sort_range) * 100
Test:
value > 10

Issue:
Too many sorts are causing temporary tables.
Recommendation:
Consider increasing sort_buffer_size and/or read_rnd_buffer_size, depending on your system memory limits.
Justification:
Temporary tables average: 17.28 per minute, this value should be less than 1 per hour.
Used variable / formula:
Sort_merge_passes / Uptime
Test:
value * 60 * 60 > 1

**Comment by extreme4all** [comment]
not api related
