### ISSUE TITLE
There are lots of rows being sorted.

### ISSUE THREAD

**Issue by Ferrariic** [Bot-detector/Bot-Detector-Core-Files#257]
Issue:
There are lots of rows being sorted.
Recommendation:
While there is nothing wrong with a high amount of row sorting, you might want to make sure that the queries which require a lot of sorting use indexed columns in the ORDER BY clause, as this will result in much faster sorting.
Justification:
Sorted rows average: 62.58 per second
Used variable / formula:
Sort_rows / Uptime
Test:
value * 60 >= 1

**Comment by extreme4all** [comment]
not api related
