### ISSUE TITLE
The rate of reading the first index entry is high.

### ISSUE THREAD

**Issue by Ferrariic** [Bot-detector/Bot-Detector-Core-Files#259]
Issue:
The rate of reading the first index entry is high.
Recommendation:
This usually indicates frequent full index scans. Full index scans are faster than table scans but require lots of CPU cycles in big tables, if those tables that have or had high volumes of UPDATEs and DELETEs, running 'OPTIMIZE TABLE' might reduce the amount of and/or speed up full index scans. Other than that full index scans can only be reduced by rewriting queries.
Justification:
Index scans average: 4.72 per minute, this value should be less than 1 per hour
Used variable / formula:
Handler_read_first / Uptime
Test:
value * 60 * 60 > 1

**Comment by extreme4all** [comment]
not api related
