### ISSUE TITLE
The rate of reading data from a fixed position is high.

### ISSUE THREAD

**Issue by Ferrariic** [Bot-detector/Bot-Detector-Core-Files#260]
Issue:
The rate of reading data from a fixed position is high.
Recommendation:
This indicates that many queries need to sort results and/or do a full table scan, including join queries that do not use indexes. Add indexes where applicable.
Justification:
Rate of reading fixed position average: 9.55 per minute, this value should be less than 1 per hour
Used variable / formula:
Handler_read_rnd / Uptime
Test:
value * 60 * 60 > 1

**Comment by extreme4all** [comment]
not api related
