### ISSUE TITLE
MyISAM key buffer (index cache) % used is low

### ISSUE THREAD

**Issue by Ferrariic** [Bot-detector/Bot-Detector-Core-Files#262]
Issue:
MyISAM key buffer (index cache) % used is low.
Recommendation:
You may need to decrease the size of key_buffer_size, re-examine your tables to see if indexes have been removed, or examine queries and expectations about what indexes are being used.
Justification:
max % MyISAM key buffer ever used: 0%, this value should be above 95%
Used variable / formula:
Key_blocks_used * key_cache_block_size / key_buffer_size * 100
Test:
value < 95

**Comment by extreme4all** [comment]
not api related
