### ISSUE TITLE
Too many clients are aborted.

### ISSUE THREAD

**Issue by Ferrariic** [Bot-detector/Bot-Detector-Core-Files#264]
Issue:
Too many clients are aborted.
Recommendation:
Clients are usually aborted when they did not close their connection to MySQL properly. This can be due to network issues or code not closing a database handler properly. Check your network and code.
Justification:
100% of all clients are aborted. This value should be below 2%
Used variable / formula:
Aborted_clients / Connections * 100
Test:
value > 2

Issue:
Too many clients are aborted.
Recommendation:
Clients are usually aborted when they did not close their connection to MySQL properly. This can be due to network issues or code not closing a database handler properly. Check your network and code.
Justification:
Aborted client rate is at 24.36 per second, this value should be less than 1 per hour
Used variable / formula:
Aborted_clients / Uptime
Test:
value * 60 * 60 > 1

**Comment by extreme4all** [comment]
not api related
