### ISSUE TITLE
The InnoDB log file size is not an appropriate size, in relation to the InnoDB buffer pool.

### ISSUE THREAD

**Issue by Ferrariic** [Bot-detector/Bot-Detector-Core-Files#265]
Issue:
The InnoDB log file size is not an appropriate size, in relation to the InnoDB buffer pool.
Recommendation:
Especially on a system with a lot of writes to InnoDB tables you should set innodb_log_file_size to 25% of innodb_buffer_pool_size. However the bigger this value, the longer the recovery time will be when database crashes, so this value should not be set much higher than 256 MiB. Please note however that you cannot simply change the value of this variable. You need to shutdown the server, remove the InnoDB log files, set the new value in my.cnf, start the server, then check the error logs if everything went fine. See also this blog entry
Justification:
Your InnoDB log size is at 0% in relation to the InnoDB buffer pool size, it should not be below 20%
Used variable / formula:
(innodb_log_file_size * innodb_log_files_in_group)/ innodb_buffer_pool_size * 100
Test:
value < 20 && innodb_log_file_size / (1024 * 1024) < 256

**Comment by extreme4all** [comment]
not api
