### ISSUE TITLE
add model table and v1/model/ routes 

### ISSUE THREAD

**Issue by Ferrariic** [Bot-detector/Bot-Detector-Core-Files#275]
This would be a combined table upon predictions and player feedback - it would be used to monitor for accuracy and model drift in the plugin. This could be output in the discord for ML developers, in order to to see daily accuracy and feedback metrics.

**Comment by extreme4all** [comment]
monitoring ML accuracy etc is not in scope of the api but the machine learning repository.
to support this the ML service needs its own database
