### ISSUE TITLE
Improve RSN transfer

### ISSUE THREAD

**Issue by Ferrariic** [Bot-detector/Bot-Detector-Core-Files#276]
As players wish to transfer their RSN to another account, we may want to allow them access to this process - in the same way that CML/other applications allow for this process. This way their KC in-game will transfer over to their new RSN.

Website: Add a page on the website to transfer data over.
This would require the following fields:

- Old RSN
- New RSN
- Temporary token (15 minute expiry)

Discord:
- User must have both RSNs linked to their discord account.
- Request a name change through the discord, where they will be given a temporary token

[PUT] Route:
- Old RSN
- New RSN
- Token
Route logic:
Compare all fields and make sure if valid, and make sure that the token is not expired. 
Complete the transfer, may have to iterate through a sql.limit(1000) in order to complete the process, if you don't batch this process it will fail.

+ Add Table in discord database for temporary token | date created | discord ID

Other information:
Limit to 1 successful token per day per discord ID transfer.

**Comment by extreme4all** [comment]
not related to database.
api already supports this:
see https://github.com/Bot-detector/Bot-Detector-Core-Files/blob/develop/api/routers/report.py#L89

```
@router.put("/v1/report", tags=["Report"])
async def update_reports(old_user_id: int, new_user_id: int, token: str):
    '''
        Update the reports from one reporting user to another.
    '''
    await verify_token(token, verification='verify_ban', route='[PUT]/v1/report/')
    # can be used for name change

    sql = update(Report)
    sql = sql.values(Report.reportingID == new_user_id)
    sql = sql.where(Report.reportingID == old_user_id)

    async with get_session(EngineType.PLAYERDATA) as session:
        await session.execute(sql)

    return {'OK': 'OK'}
```
we need a method to authenticate the user before allowing the user to do this, the only service that has this information is the discord service
