### ISSUE TITLE
Add route for banned player name querying for the website

### ISSUE THREAD

**Issue by Ferrariic** [Bot-detector/Bot-Detector-Core-Files#287]
For now this route will require a token

**Comment by extreme4all** [comment]
route already exists
[@router.get("/v1/player/bulk", tags=["Player"])](https://github.com/Bot-detector/Bot-Detector-Core-Files/blob/develop/api/routers/player.py#L61)

**Comment by Ferrariic** [comment]
Filter needs to be added
