### ISSUE TITLE
Add 'count' field to report/latest/bulk

### ISSUE THREAD

**Issue by Ferrariic** [Bot-detector/Bot-Detector-Core-Files#289]
At the moment pre-checking the report/latest/bulk with 'count' reduces the load needed by the server to send data over to the client. This is a cost-saving measure as not including it can crash the /docs# page, as well as become an unnecessary burden on a client only looking to have the count of the number of reports found in an area. 

Therefore, adding a small script for 'count' as a bool option to the already existing route for report/latest/bulk is extremely beneficial. This has been proven to take a fraction of the time in testing, than to not include this filter.

**Comment by extreme4all** [comment]
not a fan of adding business logic to api routes

**Comment by Ferrariic** [comment]
I get that, but there's some leeway needed because it's inefficient to send over the entire report latest table when all you need is a count.

**Comment by extreme4all** [comment]
arguably we are less limited by bandwith then cpu, also this is all internal networking.

**Comment by Ferrariic** [comment]
That's a fair point. An additional question is since we have limits/pages on our routes should we also include counts?

Since the routes are internal, that would effectively resolve this issue.

**Comment by extreme4all** [comment]
can you explain the first sentence:
An additional question is since we have limits/pages on our routes should we also include counts?

**Comment by Ferrariic** [comment]
So since we take care of limits as a parameter in the fast api route - we could also add count to all routes where we expect more than one row response - in places where limit is not listed. However this would really only apply if the route's response is low or bogged down due to bandwidth,  which is not the case here - since the client can always take the length of the response on their end.

**Comment by extreme4all** [comment]
i'm still not entirely sure what we are counting in this case?
The api's responsiblity is providing access to the db & data, any business logic should be applied to the business services.

**Comment by Ferrariic** [comment]
It handled business logic with the count, but since this is an internal route the issue can be closed - as the original constraint was a concern with time.
