### ISSUE TITLE
Resolve Deadlocks

### ISSUE THREAD

**Issue by Ferrariic** [Bot-detector/Bot-Detector-Core-Files#315]
Ever increasing deadlocks make this a high priority, all other issues should be on standby until this is resolved.

**Comment by extreme4all** [comment]
hotfix is a branch on main, this issue is purely for tracking purposes.
to refine: a solution/plan of action has to be thought out before implementing

**Comment by Ferrariic** [comment]
![image](https://user-images.githubusercontent.com/5789682/148350701-478f0391-5fae-496f-8aa7-443dadce03eb.png)
Suggested method of resolving the issue based upon our talk. This would also include adding additional temporary tables to handle incoming data, and round-robin spread the load across those tables - when a deadlock is detected.

**Comment by Ferrariic** [comment]
FIXED:
Raised KeyError exception in legacy-debug which stalled EVERYTHING.
