### ISSUE TITLE
legacy debug post report to v1/report

### ISSUE THREAD

**Issue by Ferrariic** [Bot-detector/Bot-Detector-Core-Files#345]
This includes changes on legacy-debug so that we can shift over to v1 (ex. report route)

**Comment by extreme4all** [comment]
Can you describe what input data should result in what output?
e.g.
what would be considered valid input & invalid input

**Comment by Ferrariic** [comment]
honestly, there's a lot - I was just going to use this issue to keep track of changes.

**Comment by Ferrariic** [comment]
tbh I'll close this issue actually since it's a duplicate of another issue.

**Comment by Ferrariic** [comment]
https://github.com/Bot-detector/Bot-Detector-Core-Files/issues/274

dupe of this one

**Comment by extreme4all** [comment]
this is a perfectly scoped issue and not duplicate, the other one had too much.
so here is what the development workflow should be
```
development workflow:
	issue (story): describing the feature
	issue refinement: 
		forumulate functional requirements
		tag issue
	commit issue to project plan (sprint planning)
	branch develop(ment)
		Draft Pull Request (link to issue)
		Write unit test
			based on functional requirements
		Develop feature
		test with unit test
		Pull request
	Review code (admin)
		code style (linting)
		validate unit test
		validate unit test results
		manual test
		approve/request change
```
can you describe the functional requirements as such that we can write test cases for them?
