### ISSUE TITLE
Be able to swap database engines

### ISSUE THREAD

**Issue by ThorntonMatthewD** [Bot-detector/Bot-Detector-Core-Files#351]
Be able to swap out engines in use as needed. Specifically the functionality I'd like to add is to be able to switch to our development/staging databases whenever running automated tests.

**Comment by extreme4all** [comment]
if we use dependencies
https://fastapi.tiangolo.com/tutorial/sql-databases/#create-the-database-tables
then we can override the database during testing
https://fastapi.tiangolo.com/advanced/testing-database/

**Comment by extreme4all** [comment]
@ThorntonMatthewD still needed?
we could use extra context

**Comment by ThorntonMatthewD** [comment]
I was overthinking this. We can just pass in a different env values to our API under test, or if that doesn't work we can just monkeypatch any env vars (like the db connection string) https://docs.pytest.org/en/7.1.x/reference/reference.html#pytest.MonkeyPatch.setenv

Gonna close this out.
