### ISSUE TITLE
Add pytest to github actions

### ISSUE THREAD

**Issue by Ferrariic** [Bot-detector/Bot-Detector-Core-Files#352]
https://blog.dennisokeeffe.com/blog/2021-08-08-pytest-with-github-actions

This blog outlines the method fairly well - we could use this to implement pytest for our routes on github actions.

**Comment by LukeHankey** [comment]
I could do this. Have added it in another project of mine.

**Comment by extreme4all** [comment]
Awsome!

**Comment by Ferrariic** [comment]
> I could do this. Have added it in another project of mine.

That would be excellent! Let us know if you need any help.
