### ISSUE TITLE
Route-level health checks

### ISSUE THREAD

**Issue by Ferrariic** [Bot-detector/Bot-Detector-Core-Files#353]
**issue (story): describing the feature**
I would like to be able to check the specific route-level health of our API. This would alert myself, as a user and as a developer, to latencies, and % of the response codes generated by each route. To accomplish this, I would like an endpoint in the format of **osrsbotdetector.com/dev/health** which would output the following information over the course of one hour.

| Route Name | Recent Response Code | Response Code Breakdowns | min Latency | max Latency  | average Latency | Percent of queries with raised exceptions |
| --- | --- | --- | --- | --- | --- | --- |
| /report/ | 200 (98%) | [(400, 1%), (500, 1%)] | 20ms | 400ms | 200ms | 4% |

This may be possible by adding a wrapper to each route, which would log this information and be accessible via the /health/ route.
This route could be queried by any player, and would be intended to be used by the discord bot to check for server health occasionally, and perhaps on the site itself.

Workflow logic:
> Is [GET]/health/ accessible? --> No (API is down)
> Is [GET]/health/ accessible? --> Yes (API is up) --> Are the routes within working order --> Yes ({'ok':'ok'}) | No (Print dead routes & breakdown).

In order to detect dead routes, the [GET]/health/ route would need the following checks:

- Route Name or ID | str # Check this route, if None check all routes
- Maximum Min Latency | int # Return all routes above this maximum min latency
- Maximum Max Latency | int # Return all routes above this maximum max latency
- Maximum Avg Latency | int # Return all routes above this maximum avg latency
- Maximum percent of queries with raised exceptions # Return all routes above the maximum number of exceptions
- Maximum Failed Responses | int # Return all routes with a number of failed responses greater than this amount.

**Comment by extreme4all** [comment]
not in scope of the api, alerting & metrics should be done by Grafana loki (log aggregator & dashboarding)
