### ISSUE TITLE
Verification Issue: !Code with leading zero

### ISSUE THREAD

**Issue by Ferrariic** [Bot-detector/Bot-Detector-Core-Files#359]
Issue related to entry: 2298 in DiscordVerification

Code with leading zero 0734 entered in database as 734 - the in-game message states "USER has been verified" though the database entry does not update.

**Comment by ThorntonMatthewD** [comment]
https://github.com/Bot-detector/bot-detector-discord-bot/pull/112 This is the main fix. I want to make sure codes are at least 4 digits coming out of the database on the API end as well. I'm not going to check the user input so a user typing in `!code 52` doesn't have it treated as `!code 0052` on the backend. That would get funky fast.
