### ISSUE TITLE
update workflow

### ISSUE THREAD

**Issue by extreme4all** [Bot-detector/Bot-Detector-Core-Files#38]
the workflow on readme is outdated, please update it to more accuratly reflect the current situation
plugin => names =>hiscores => ML => jmod => names (confirmed ban, confirmed player)
hiscores => names (potential ban)

**Comment by Ferrariic** [comment]
![image](https://user-images.githubusercontent.com/5789682/115799081-b7972780-a3a5-11eb-8502-d5d28261ebf1.png)
