### ISSUE TITLE
Add a way to get deduplicated total from `/v1/report/count`

### ISSUE THREAD

**Issue by Cyborger1** [Bot-detector/Bot-Detector-Core-Files#383]
Currently the route gives info for manual `true`/`false`, but adding the two together to get the total means it will be double counted.

**Comment by extreme4all** [comment]
ooh, this is what you mean, hmm

**Comment by extreme4all** [comment]
because manual detect can only happen when you see the player in game, than the player is also detected via the automatic detect.
