### ISSUE TITLE
Remove Breakdown Prediction for Stats too Low

### ISSUE THREAD

**Issue by Ferrariic** [Bot-detector/Bot-Detector-Core-Files#436]
We'd like to do the following: 
1. In cases of Stats too low (ex. an account below 2m xp) we would remove the breakdown predictions, as they're not entirely relevant.

Let us know if you think this would be a good change ✅ , or to keep the current system ❌.
✅ 55
❌ 5

**Comment by Cyborger1** [comment]
Done on API side with #440.

Fully resolved after https://github.com/Bot-detector/bot-detector/pull/161 is merged.
