### ISSUE TITLE
Do not provide a confidence rating for "Stats Too Low"

### ISSUE THREAD

**Issue by Cyborger1** [Bot-detector/Bot-Detector-Core-Files#441]
Now that the breakdown is removed by default for these accounts, the confidence rating should be omitted as it makes it confusing. Anything that's not an actual label should not have a rating.

![image](https://user-images.githubusercontent.com/45152844/184289483-0c83f366-08b7-48bd-9429-05df6c2d8cc1.png)

For the plugin side, consider sending "null" or no confidence for these cases. This will require slight changes to the plugin to handle, but it'll allow me to not display a number. Tentative commit is here: https://github.com/Cyborger1/bot-detector/commit/2e812121d572891ba28dbdbd03901e1c62fe2e73

Note for above commit: Make sure the Feedback route can handle null confidence, else I can make it send 0 instead.
Also, if this change is implemented, then the breakdown API parameter recently added can be removed as I can infer from the confidence being null to hide the breakdown.

**Comment by extreme4all** [comment]
> For the plugin side, consider sending "null" or no confidence for these cases.
This sounds good to me!
> Also, if this change is implemented, then the breakdown API parameter recently added can be removed as I can infer from the confidence being null to hide the breakdown.
I prefer that users can optionally choose to show the breakdown, but the default will be to not show.

> Make sure the Feedback route can handle null confidence, else I can make it send 0 instead.
I'm not entirely sure what the preferred solution for this is

**Comment by Cyborger1** [comment]
All I need is for the prediction confidence to be null to know if the optional config be applied. The advantage of this approach would be that it avoids what is essentially UI logic being handled by the API.

I also think the confidence should always be null when the label field is not an actual label.
